<a href="https://colab.research.google.com/github/maybje/CE888_2020/blob/master/Lab1/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CE888 - Lab 1

Laboratory 1 for Data Science and Decision Making


1. Create a (4 x 2) integer array and print it's attributes

In [0]:
import numpy as np

In [4]:
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(a)
print("Shape of a: ", a.shape)
print("Number of dimensions: ", a.ndim)
print("Size of a: ", a.size)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape of a:  (4, 2)
Number of dimensions:  2
Size of a:  8


2. Create an array of dimension (1,10) and sort it in ascending and descending order

In [21]:
b=np.random.randint(1,100,10)
print(b)

print("This is b in ascending order: ", np.sort(b))
print("This is b in descending order: ", -np.sort(-b))



[23 95 25 91 83 39 87 73 37 55]
This is b in ascending order:  [23 25 37 39 55 73 83 87 91 95]
This is b in descending order:  [95 91 87 83 73 55 39 37 25 23]


3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [33]:
c=np.array([1, 2 ,3 ,4 ,5, 6, 7, 8, 9])

print("2D array: ", "\n", c.reshape(3,3))

2D array:  
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


4. Stack two arrays of any size horizontally and vertically

In [99]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])

c=np.concatenate((a,b),axis=1)
print("Horizontal: ", "\n", np.hstack((a,b)))
print("Vertical: ", "\n",  np.vstack((a,b)))

Horizontal:  
 [[1 2 5 6]
 [3 4 7 8]]
Vertical:  
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


5.Create two array of same size and find commom elements

In [65]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[5,6],[7,8],[9,10]])

common=np.isin(a,b)
print("Common elements: ", "\n", a[common])

Common elements:  
 [5 6]


6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [69]:
a=np.random.randint(1,100, (5,5))
print(a)
print("Max value from each row: ", "\n", np.amax(a, axis=1))
print("Max value from each column: ", "\n", np.amax(a, axis=0))

[[18 81 77 77 71]
 [ 1 51 43 57 68]
 [40 23 20 53 13]
 [16 17 34 48 28]
 [49 36 10 41 44]]
Max value from each row:  
 [81 68 53 48 49]
Max value from each column:  
 [49 81 77 77 71]


7. Create an array of size 100 and compute the mean, median, standard deviation.

In [73]:
a=np.random.randint(1,100, (100))
print(a)

print("Mean: ", np.mean(a))
print("Median: ", np.median(a))
print("Standard Deviation: ", np.std(a))

[27 72 53 45  7 51  9 70 53 40 15 66 18 60 92 43 90 96 54 25 58 23 77 96
 74 30  9 30  5 59 14 78 25 81 24 68 87 35 78 85 52 49 58 21 71 34 82 12
 15 19 20  1 43 11 64 74 96 82 72 23 82 89  7 62 42 53 57 46 81 90 70 90
 20 20 71 28 40 17 19 93 43 79 53  7 13 24 46 69 79 84 93 64 39 40 23 37
 91 47 71 14]
Mean:  50.14
Median:  51.5
Standard Deviation:  27.73193826619409


8. Normalize a 5x5 random matrix

In [81]:
a=np.random.randint(1,100, (5,5))
print("Original: ", "\n", a)

print("normalized: ", "\n", (a-np.mean(a))/np.std(a))

Original:  
 [[ 4 79 32 93 42]
 [91 48 37 69  8]
 [26 86 25 51  3]
 [66 49 94 85 34]
 [90 57 67 84 93]]
normalized:  
 [[-1.79366229  0.76773664 -0.83740669  1.24586444 -0.49588683]
 [ 1.17756047 -0.29097492 -0.66664676  0.42621678 -1.65705435]
 [-1.0423186   1.00680054 -1.07647059 -0.18851896 -1.82781427]
 [ 0.32376082 -0.25682293  1.28001642  0.97264855 -0.76910272]
 [ 1.14340848  0.01639295  0.35791281  0.93849657  1.24586444]]


9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [126]:
a=np.random.randint(1,10, (4,4,3))
a2=np.reshape(a,(4,12))


b=np.random.randint(1,10, (4,4))


print(a*b[:,:,None])

[[[32 12 12]
  [ 6  2 12]
  [32 48 40]
  [ 8  4  8]]

 [[24 20 12]
  [ 8 24 36]
  [81 36 81]
  [ 3  6 18]]

 [[54 12  6]
  [30 10 30]
  [63  7  7]
  [ 6 12 27]]

 [[45  9 27]
  [32 72 56]
  [54 27 27]
  [56  7 63]]]
